pub mod send_email_when_user_created;
pub mod send_email_when_user_deactivated;
pub mod send_email_when_user_email_changed;
pub mod send_email_when_user_reactivated;
pub mod send_email_when_user_suspended;
pub mod send_email_when_user_unlocked;
pub mod send_email_when_user_username_changed;

pub use send_email_when_user_created::SendEmailWhenUserCreatedHandler;
pub use send_email_when_user_deactivated::SendEmailWhenUserDeactivatedHandler;
pub use send_email_when_user_email_changed::SendEmailWhenUserEmailChangedHandler;
pub use send_email_when_user_reactivated::SendEmailWhenUserReactivatedHandler;
pub use send_email_when_user_suspended::SendEmailWhenUserSuspendedHandler;
pub use send_email_when_user_unlocked::SendEmailWhenUserUnlockedHandler;
pub use send_email_when_user_username_changed::SendEmailWhenUsernameChangedHandler;
